### PR TITLE
webforai can now be run from the cli

### PR DESCRIPTION
**Pull request by moons-14**
By simply running `npx webforai`, you can now convert URLs or local HTML files to Markdown.
This tool supports both interactive input and command-line arguments for specifying source and output paths, enabling intuitive and efficient usage.

## Examples of usage
- `npx webforai https://example.com example.md`
- `npx webforai https://example.com --loader=playwright`

### CODE REVIEW

**Comment by inaridiy** [comment]
I'm starting to wonder what to do with the lisence notation in build.ts. As it is, every time someone edits build.ts, the name will increase.

[packages/webforai/build.ts](https://github.com/inaridiy/webforai/pull/30/files#diff-e49a01ee5781eec31c90cfb8fdd6903c47a6ccb6512017d1559b9d439b57186b)

@moons-14

**Comment by moons-14** [comment]
Here's a natural translation of the given text:

The license of Honojs states:

```
Copyright (c) 2021 - present, Yusuke Wada and Hono contributors
```
https://github.com/honojs/hono/blob/main/LICENSE

Similarly, for this repository's license, if we add the phrase "webforai contributors" to the license in all files, there would likely be no need to specifically mention my name.

@inaridiy

**Comment by moons-14** [comment]
I'd like to implement a few more additional features, so the merge can wait.

**Comment by moons-14** [comment]
We implemented all the features we wanted to implement.
All that's left is the license.

**Comment by moons-14** [comment]
TODO: Ensure that the test does not fail after editing the README

**Pull request merged**
